{{- if .Values.kedaScaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web.fullname" . }}-scaler
spec:
  scaleTargetRef:
    name: {{ include "simple-web.fullname" . }}
  cooldownPeriod: {{ .Values.kedaScaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaScaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.kedaScaling.maxReplicaCount}}
  triggers:
    {{- if .Values.kedaScaling.cpu.enabled }}
    - type: cpu
      metadata:
        {{- toYaml .Values.kedaScaling.cpu | nindent 8 }}
    {{- end }}
    {{- if .Values.kedaScaling.memory.enabled }}
    - type: memory
      metadata:
        {{- toYaml .Values.kedaScaling.memory | nindent 8 }}
    {{- end }}
    {{- if .Values.kedaScaling.cron.enabled }}
    - type: cron
      metadata:
        {{- toYaml .Values.kedaScaling.cron | nindent 8 }}
    {{- end }}
{{- end }}